export const employees = [
    {
      id: 1,
      name: "Aino Virtanen",
      title: "HR Manager",
      salary: 4200,
      phone: "040-1234567",
      email: "aino.virtanen@example.com",
      animal: "Owl",
      startDate: "2018-04-01",
      location: "Helsinki",
      department: "Human Resources",
      skills: ["Recruiting", "Communication", "Employee Relations"],
    },
    {
      id: 2,
      name: "John Doe",
      title: "Software Engineer",
      salary: 5000,
      phone: "050-9876543",
      email: "john.doe@example.com",
      animal: "Dog",
      startDate: "2023-11-01",
      location: "New York",
      department: "Engineering",
      skills: ["JavaScript", "React", "Node.js"],
    },
    {
      id: 3,
      name: "Jane Smith",
      title: "Product Manager",
      salary: 6200,
      phone: "045-6789012",
      email: "jane.smith@example.com",
      animal: "Cat",
      startDate: "2015-04-01",
      location: "London",
      department: "Product",
      skills: ["Leadership", "Agile", "Stakeholder Management"],
    },
    // Add 7 more employees with varying start dates and roles
  ];